### ISSUE TITLE
Sets (and probably other types) do not work

### ISSUE THREAD

**Issue by psarka** [sksamuel/avro4k#17]
The Types table lists `Set<T>` as a supported type, but it does not work, (or I'm doing it wrong). The following example

```
import com.sksamuel.avro4k.Avro
import kotlinx.serialization.Serializable

@Serializable
data class S(val t: Set<Int>)

fun main() {
   val r = Avro.default.toRecord(S.serializer(), S(setOf(1)))
   val back = Avro.default.fromRecord(S.serializer(), r)  // this line fails
}
```

fails with the following error:

```
Exception in thread "main" kotlinx.serialization.SerializationException: class com.sksamuel.avro4k.decoder.ListDecoder can't retrieve untyped values
	at kotlinx.serialization.ElementValueDecoder.decodeValue(ElementWise.kt:106)
	at kotlinx.serialization.ElementValueDecoder.decodeInt(ElementWise.kt:115)
	at kotlinx.serialization.internal.IntSerializer.deserialize(Primitives.kt:66)
	at kotlinx.serialization.internal.IntSerializer.deserialize(Primitives.kt:62)
	at com.sksamuel.avro4k.decoder.ListDecoder.decodeSerializableValue(ListDecoder.kt:60)
	at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:142)
	at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:89)
	at kotlinx.serialization.internal.ListLikeSerializer.readAll(CollectionSerializers.kt:85)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.patch(CollectionSerializers.kt:35)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:49)
	at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Coders.kt:113)
	at kotlinx.serialization.ElementValueDecoder.decodeSerializableValue(ElementWise.kt:91)
	at kotlinx.serialization.ElementValueDecoder.decodeSerializableElement(ElementWise.kt:142)
	at S$$serializer.deserialize(set.kt)
	at S$$serializer.deserialize(set.kt:5)
	at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Coders.kt:113)
	at kotlinx.serialization.ElementValueDecoder.decodeSerializableValue(ElementWise.kt:91)
	at com.sksamuel.avro4k.Avro.fromRecord(Avro.kt:222)
	at SetKt.main(set.kt:15)
	at SetKt.main(set.kt)
```

Tested on current master.

**Comment by sksamuel** [comment]
Thanks, fixed and I've released 0.23.0
