### ISSUE TITLE
Issue decoding Avro4k data classes: Error deserializing key/value for partition

### ISSUE THREAD

**Issue by KushalP** [sksamuel/avro4k#59]
It's not clear where I'm going wrong, but I'm trying to use Kafka, the Kafka Schema Registry, and Avro4k together.

I'm seeing the exception below with the code I've provided further down as a `kotest` test case.

I'm probably doing something wrong here. Any tips would be much appreciated :pray: 

## Exception

```
Error deserializing key/value for partition sample-event-topic-0 at offset 0. If needed, please seek past the record to continue consumption.
org.apache.kafka.common.errors.SerializationException: Error deserializing key/value for partition sample-event-topic-0 at offset 0. If needed, please seek past the record to continue consumption.
	(Coroutine boundary)
	at io.kotest.core.runtime.TestExecutor$executeAndWait$2$1$3.invokeSuspend(TestExecutor.kt:176)
	at io.kotest.core.runtime.ReplayKt.replay(replay.kt:19)
	at io.kotest.core.runtime.TestExecutor$executeAndWait$2$1.invokeSuspend(TestExecutor.kt:175)
	at io.kotest.core.runtime.TestExecutor.executeAndWait-xkB6VbI(TestExecutor.kt:168)
	at io.kotest.core.runtime.TestExecutor.invokeTestCase(TestExecutor.kt:150)
	at io.kotest.core.runtime.TestExecutor.executeActiveTest(TestExecutor.kt:117)
	at io.kotest.core.runtime.TestExecutor$intercept$2.invokeSuspend(TestExecutor.kt:74)
	at io.kotest.core.runtime.TestExecutor.executeIfActive(TestExecutor.kt:86)
	at io.kotest.core.runtime.TestExecutor.intercept(TestExecutor.kt:74)
	at io.kotest.core.runtime.TestExecutor.execute(TestExecutor.kt:55)
	at io.kotest.core.engine.SingleInstanceSpecRunner.runTest(SingleInstanceSpecRunner.kt:62)
	at io.kotest.core.engine.SingleInstanceSpecRunner$execute$2.invokeSuspend(SingleInstanceSpecRunner.kt:73)
	at io.kotest.core.engine.SingleInstanceSpecRunner$execute$3.invokeSuspend(SingleInstanceSpecRunner.kt:79)
	at io.kotest.core.engine.SpecExecutor$runTests$run$1.invokeSuspend(SpecExecutor.kt:105)
	at io.kotest.core.engine.SpecExecutor.runTests(SpecExecutor.kt:108)
	at io.kotest.core.engine.SpecExecutor.execute(SpecExecutor.kt:36)
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing key/value for partition sample-event-topic-0 at offset 0. If needed, please seek past the record to continue consumption.
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id 9
Caused by: org.apache.kafka.common.errors.SerializationException: SampleEvent specified by the writers schema could not be instantiated to find the readers schema.
```

## Code to reproduce the problem

```kotlin
class SampleAvro4kProducerConsumerExceptionSpec : StringSpec({
    val bootstrapServers = "kafka:9092"
    val schemaRegistryUrl = "kafka-schema-registry:7081"
    val topic = "sample-event-topic"

    "consuming from an Avro4k producer causes an exception" {
        val consumer = SampleEventConsumer(bootstrapServers, schemaRegistryUrl, topic)
        val producer = SampleEventProducer(bootstrapServers, schemaRegistryUrl, topic)

        val uuid = UUID.randomUUID().toString()
        val metadata = producer.publish(uuid, SampleEvent("foo-$uuid", "bar-$uuid")).get()
        println("Published event with offset ${metadata.offset()}")

        // TODO: This should not throw and should consume messages.
        shouldThrow<SerializationException> {
            consumer.poll()
        }.message shouldContain("Error deserializing key/value for partition")
    }
})

class SampleEventConsumer(
    bootstrapServers: String,
    schemaRegistryUrl: String,
    topic: String
) : AutoCloseable {
    private val consumerConfig = mapOf(
        ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG to bootstrapServers,
        ConsumerConfig.GROUP_ID_CONFIG to UUID.randomUUID().toString(),
        ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG to "true",
        ConsumerConfig.AUTO_OFFSET_RESET_CONFIG to "earliest",
        ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG to StringDeserializer::class.java,
        ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG to SampleEvent.Deserializer::class.java,
        KafkaAvroDeserializerConfig.SCHEMA_REGISTRY_URL_CONFIG to schemaRegistryUrl,
        KafkaAvroDeserializerConfig.SPECIFIC_AVRO_READER_CONFIG to "true"
    )

    private val consumer = KafkaConsumer<String, SampleEvent>(consumerConfig).apply {
        subscribe(listOf(topic))
    }

    fun poll(): ConsumerRecords<String, SampleEvent> = consumer.poll(Duration.ofSeconds(1))

    override fun close() = consumer.close()
}

class SampleEventProducer(
    bootstrapServers: String,
    schemaRegistryUrl: String,
    private val topic: String
) : AutoCloseable {
    private val producerConfig = mapOf(
        ProducerConfig.BOOTSTRAP_SERVERS_CONFIG to bootstrapServers,
        ProducerConfig.ACKS_CONFIG to "all",
        ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG to StringSerializer::class.java,
        ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG to SampleEvent.Serializer::class.java,
        KafkaAvroSerializerConfig.SCHEMA_REGISTRY_URL_CONFIG to schemaRegistryUrl
    )

    private val producer = KafkaProducer<String, SampleEvent>(producerConfig)

    fun publish(key: String, value: SampleEvent): Future<RecordMetadata> =
        producer.send(ProducerRecord(topic, key, value))

    override fun close() = producer.close()
}

@Serializable
data class SampleEvent(
    val foo: String,
    val bar: String
) {
    class Serializer : KafkaSerializer<SampleEvent>(serializer())
    class Deserializer : KafkaDeserializer<SampleEvent>(serializer())
}

open class KafkaSerializer<T> private constructor(
    private val serializer: SerializationStrategy<T>,
    private val kafkaSerializer: KafkaAvroSerializer
) : Serializer<T> {
    constructor(serializer: SerializationStrategy<T>) : this(serializer, KafkaAvroSerializer())

    override fun serialize(topic: String?, data: T): ByteArray =
        Avro.default.toRecord(serializer, data).let { kafkaSerializer.serialize(topic, it) }

    override fun configure(configs: MutableMap<String, *>?, isKey: Boolean) = kafkaSerializer.configure(configs, isKey)

    override fun close() = kafkaSerializer.close()
}



open class KafkaDeserializer<T> private constructor(
    private val deserializer: DeserializationStrategy<T>,
    private val kafkaDeserializer: KafkaAvroDeserializer
) : Deserializer<T> {
    constructor(serializer: DeserializationStrategy<T>) : this(serializer, KafkaAvroDeserializer())

    override fun deserialize(topic: String?, data: ByteArray): T =
        (kafkaDeserializer.deserialize(topic, data) as GenericRecord).let { record ->
            Avro.default.fromRecord(deserializer, record)
        }

    override fun configure(configs: MutableMap<String, *>?, isKey: Boolean) = kafkaDeserializer.configure(configs, isKey)

    override fun close() = kafkaDeserializer.close()
}
```

**Comment by KushalP** [comment]
I have figured out my own problem. The error here is the following configuration line:

```kotlin
KafkaAvroDeserializerConfig.SPECIFIC_AVRO_READER_CONFIG to "true"
```

Avro4k doesn't produce a `SpecificRecord`, so it fails to find a suitable class.

With that removed, it all works as expected.

Hopefully this is useful for anyone else who has a similar problem in the future.
